name: CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2


      - name: Setup tmate session
        uses: mxschmitt/action-tmate@v3

      - name: install.sh
        run: ./install.sh --git-sha $GITHUB_SHA

